version: '3'
services:
    messaging:
        image: 'rabbitmq:3-management'
    frontend:
        image: 'bitnami/tomcat'
    backend:
         image: 'python:3.7-alpine'
    mysql:
        image: 'mysql'
        environment:
            MYSQL_ROOT_PASSWORD: changeme
